/*
 * LISTE DE PISTES D'AMELIORATIOn
 * 
 * AVOIR UNE COPIE DU TABLEAU QUE L'ON MANIPULE HORS AFFICHAGE + UNE COPIE QUE L'ON AFFICHE A INTERVAL REGULIER
 * AVOIR UNE COPIE DU TABLEAU QUE L'ON MANIPULE POUR LES TRANSFORMATIONS
 *
 * MOVE & COPY ACTIONS
 * 
 * DEFINIR LE REFERENTIEL X,Y,Z
 * 
 */
